AWSTemplateFormatVersion: '2010-09-09'

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow Access to Web Port and pg from anywhere
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"
      VpcId: !ImportValue VPC

Outputs:
  SecurityGroup:
    Description: id of security group
    Value: !Ref SecurityGroup
    Export:
      Name: SecurityGroupId