AWSTemplateFormatVersion: '2010-09-09'

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow Access to SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"
      VpcId: !ImportValue VPC

  SecurityGroupDB:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow Access to MySQL
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !GetAtt SecurityGroup.GroupId
      VpcId: !ImportValue VPC

Outputs:
  SecurityGroup:
    Description: id of security group
    Value: !Ref SecurityGroup
    Export:
      Name: SecurityGroupId
  SecurityGroupDB:
    Description: id of security group
    Value: !Ref SecurityGroupDB
    Export:
      Name: SecurityGroupIdDB