AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  DBEngine:
    Default: mysql
    Description: Type of engine
    Type: String
  DBEngineVersion:
    Default: '5.7.34'
    Description: Version of engine
    Type: String
  DBInstanceID:
    Default: reto
    Description: id of instance
    Type: String
    MinLength: '1'
    MaxLength: '63'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: >-
      Must begin with a letter and must not end with a hyphen or contain two
      consecutive hyphens.
  DBName:
    Default: reto
    Description: database name
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters.
  DBInstanceClass:
    Default: db.t3.small
    Description: DB instance class
    Type: String
    ConstraintDescription: Must select a valid DB instance type.
  DBAllocatedStorage:
    Default: '25'
    Description: The size of the database (GiB)
    Type: Number
    MinValue: '5'
    MaxValue: '1024'
    ConstraintDescription: must be between 20 and 1024 GiB.
  DBUsername:
    NoEcho: 'true'
    Description: Username for Postgresql database access
    Default: neimv
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBSecretsName:
    Description: Name of SecretsManager
    Type: String
    Default: 'NeimvRDSSecret'

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "DBSubnetGroup for RDS postgresql instance"
      DBSubnetGroupName: DBSubnetGroup
      SubnetIds:
        - !ImportValue PrivateSubnet1
        - !ImportValue PrivateSubnet2

  RDSSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
        Name: !Ref DBSecretsName
        Description: 'Secret with dynamically generated password.'
        GenerateSecretString:
            RequireEachIncludedType: true
            SecretStringTemplate: '{"username": "neimv"}'
            GenerateStringKey: 'password'
            PasswordLength: 25
            ExcludePunctuation: true

  DB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      StorageType: 'gp2'
      DBInstanceIdentifier: !Ref DBInstanceID
      DBName: !Ref DBName
      DBInstanceClass: !Ref DBInstanceClass
      DBSubnetGroupName: !Ref DBSubnetGroup
      AllocatedStorage: !Ref DBAllocatedStorage
      Engine: !Ref DBEngine
      EngineVersion: !Ref DBEngineVersion
      MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref RDSSecret, ':SecretString:username}}' ]]
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref RDSSecret, ':SecretString:password}}' ]]
      MonitoringInterval: '60'
      MonitoringRoleArn: 'arn:aws:iam::566283433843:role/rds-monitoring-role'
      DeleteAutomatedBackups: false
      DeletionProtection: false
      BackupRetentionPeriod: 1
      EnableIAMDatabaseAuthentication: false
      PubliclyAccessible: false
      VPCSecurityGroups:
        - !ImportValue SecurityGroupIdDB

Outputs:
  DatabaseName:
    Description: Instance name
    Value: !Ref DB
    Export:
      Name: DatabaseName
  DatabasePort:
    Description: Port of database
    Value: !GetAtt DB.Endpoint.Port
    Export:
      Name: DatabasePort
  DatabaseUrl:
    Description: URL of database
    Value: !GetAtt DB.Endpoint.Address
    Export:
      Name: DatabaseUrl
  DatabaseSecrets:
    Description: Arn of secretsmanager
    Value: !Ref RDSSecret
    Export:
      Name: DBSecrets
  DatabaseSecretsName:
    Description: Name of secretsmanager
    Value: !Ref DBSecretsName
    Export:
      Name: DatabaseSecretsName