AWSTemplateFormatVersion: '2010-09-09'
Description: Base infra to use with AeroCTL

Parameters:
  # Dynamo
  DynamoTable:
    Description: Dynamo name table
    Type: String
    Default: aerodrome
  DynamoKey:
    Description: Key used in dynamo
    Type: String
    Default: user_key

Resources:
  AerodromeDynamo:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
      - AttributeName: !Ref DynamoKey
        AttributeType: S
      # - AttributeName: !Ref DynamoSort
      #   AttributeType: S
      KeySchema:
      - AttributeName: !Ref DynamoKey
        KeyType: HASH
      # - AttributeName: !Ref DynamoSort
      #   KeyType: RANGE
      SSESpecification:
        SSEEnabled: true

Outputs:
  AerodromeDynamo:
    Description: Aerodrome reference to export
    Value: !Ref AerodromeDynamo
    Export:
      Name: AerodromeDynamo
  AerodromeDynamoArn:
    Description: Aerodrome ARN reference to export
    Value: !GetAtt AerodromeDynamo.Arn
    Export:
      Name: AerodromeDynamoArn