AWSTemplateFormatVersion: '2010-09-09'
Description: Base infra to use with AeroCTL

Resources:
  AerodromeSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow Access to Web Port and pg from anywhere
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: "0.0.0.0/0"
      VpcId: !ImportValue AerodromeVPC

Outputs:
  SecurityGroup:
    Description: id of security group
    Value: !Ref AerodromeSecurityGroup
    Export:
      Name: AerodromeSecurityGroupId