version: '3'

services:
  db:
    build:
      context: .
      dockerfile: mysql.dockerfile
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: reto
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  ws:
    build: .
    ports:
      - "3030:3030"
    environment:
      SQLCONNECT: "root:example@tcp(db:3306)/reto"
    depends_on:
      db:
        condition: service_healthy